#
#  Copyright 2017 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---
- name: Create clusters in the OOB vCenter
  local_action:
    module: vmware_cluster
    hostname: "{{ oob_vcenter_url }}"
    username: "{{ oob_vcenter_user_name }}"
    password: "{{ oob_vcenter_user_password }}"
    datacenter_name: "{{ oob_vcenter['datacenter_name'] }}"
    cluster_name: "{{ item['name'] }}"
    enable_ha: True
    enable_drs: True
    validate_certs: False
    state: present
  with_items:
    - "{{ oob_vcenter['clusters'] }}"
  tags:
    - create_oob_clusters

- name: Destroy clusters in the OOB vCenter
  local_action:
    module: vmware_cluster
    hostname: "{{ oob_vcenter_url }}"
    username: "{{ oob_vcenter_user_name }}"
    password: "{{ oob_vcenter_user_password }}"
    datacenter_name: "{{ oob_vcenter['datacenter_name'] }}"
    cluster_name: "{{ item['name'] }}"
    validate_certs: False
    state: present
  with_items:
    - "{{ oob_vcenter['clusters'] }}"
  tags:
    - destroy_oob_clusters

