---
- name: Create OOB Management VDS
  local_action:
    module: vmware_dvswitch
    hostname: "{{ oob_vcenter_url }}"
    username: "{{ oob_vcenter_user_name }}"
    password: "{{ oob_vcenter_user_password }}"
    datacenter_name: "{{ oob_vcenter['datacenter_name'] }}"
    switch_name: "{{ item['name'] }}"
    uplink_quantity: "{{ item['uplinks'] }}"
    mtu: 1600
    discovery_proto: lldp
    discovery_operation: both
    state: present
    validate_certs: False
  with_items: "{{ oob_vcenter['dvs'] }}"
  tags:
    - create_oob_vcenter_dvs

- name: Destroy OOB Management VDS
  local_action:
    module: vmware_dvswitch
    hostname: "{{ oob_vcenter_url }}"
    username: "{{ oob_vcenter_user_name }}"
    password: "{{ oob_vcenter_user_password }}"
    datacenter_name: "{{ oob_vcenter['datacenter_name'] }}"
    switch_name: "{{ item['name'] }}"
    uplink_quantity: "{{ item['uplinks'] }}"
    mtu: 1600
    discovery_proto: lldp
    discovery_operation: both
    state: absent
    validate_certs: False
  with_items: "{{ oob_vcenter['dvs'] }}"
  tags:
    - destroy_oob_vcenter_dvs

